### PR TITLE
Update for 2.0.4

### PR DESCRIPTION
**Pull request by blink1073**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by blink1073** [comment]
@conda-forge-admin, please rerender

**Comment by blink1073** [comment]
I added myself as a maintainer.  We depend on this package in [jupyter-events](https://github.com/conda-forge/jupyter_events-feedstock/pull/6).

**Comment by blink1073** [comment]
cc @ocefpaf

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by blink1073** [comment]
Thanks @ocefpaf!  :heart:

**Pull request merged**
